import { TemplateDefinition } from "./blank";

export const realEstateTemplate: TemplateDefinition = {
  id: "realestate",
  title: "Luxury Real Estate",
  description: "High-end property showcase with premium visuals, proof, and inquiry-focused CTAs.",
  sections: [
    {
      id: "realestate-hero",
      type: "hero",
      order: 0,
      props: {
        headline: "Signature Homes in Prime Locations",
        subheadline: "Discover architect-designed residences represented with discretion and expertise.",
        ctaText: "Browse Listings",
        ctaHref: "#",
        bgColor: "#EEF2F7",
        bgImage: "https://picsum.photos/id/1043/1920/1080",
      },
      style: {
        desktop: {
          backgroundColor: "#EEF2F7",
          minHeight: 690,
          paddingTop: 100,
          paddingBottom: 100,
          boxShadow: "inset 0 0 0 9999px rgba(238,242,247,0.4)",
        },
      },
      elements: [],
    },
    {
      id: "realestate-features",
      type: "features",
      order: 1,
      props: {
        label: "OUR EDGE",
        title: "A Refined Buying Experience",
        bgColor: "#F3F6FA",
        cardBgColor: "#FFFFFF",
        accentColor: "#334155",
        headlineColor: "#0F172A",
        bodyColor: "#475569",
        features: [
          {
            id: "re-f1",
            title: "Exclusive Inventory",
            description: "Access off-market opportunities before they appear publicly.",
            iconName: "LayoutGrid",
          },
          {
            id: "re-f2",
            title: "Market Intelligence",
            description: "Data-driven pricing and timing insights for confident decisions.",
            iconName: "MousePointer2",
          },
          {
            id: "re-f3",
            title: "Negotiation Mastery",
            description: "Protecting value while securing terms aligned with your priorities.",
            iconName: "Download",
          },
        ],
      },
      style: {
        desktop: {
          backgroundColor: "#F3F6FA",
          minHeight: 620,
          paddingTop: 92,
          paddingBottom: 92,
        },
      },
      elements: [],
    },
    {
      id: "realestate-pricing",
      type: "pricing",
      order: 2,
      props: {
        title: "Representation Packages",
        bgColor: "#111827",
        titleColor: "#E5E7EB",
        cardBackground: "rgba(148,163,184,0.14)",
        cardBorderColor: "rgba(148,163,184,0.34)",
        textColor: "#F3F4F6",
        mutedTextColor: "rgba(229,231,235,0.76)",
        badgeBackground: "#CBD5E1",
        badgeTextColor: "#0F172A",
        buttonBorderColor: "#CBD5E1",
        buttonTextColor: "#E2E8F0",
        buttonHoverBg: "#E2E8F0",
        buttonHoverText: "#111827",
        tiers: [
          {
            id: "re-p1",
            name: "Buyer Advisory",
            price: "$2,500",
            features: ["Neighborhood strategy", "Tour planning", "Offer guidance"],
            ctaText: "Start Advisory",
            ctaHref: "#",
          },
          {
            id: "re-p2",
            name: "Full Acquisition",
            price: "1.5%",
            features: ["End-to-end representation", "Negotiation and legal coordination", "Post-close support"],
            isPopular: true,
            ctaText: "Discuss Acquisition",
            ctaHref: "#",
          },
        ],
      },
      style: {
        desktop: {
          backgroundColor: "#111827",
          minHeight: 620,
          paddingTop: 92,
          paddingBottom: 92,
        },
      },
      elements: [],
    },
    {
      id: "realestate-testimonials",
      type: "testimonials",
      order: 3,
      props: {
        label: "CLIENT STORIES",
        bgColor: "#F8FAFC",
        accentColor: "#475569",
        lineColor: "#CBD5E1",
        quoteColor: "#111827",
        authorColor: "#0F172A",
        roleColor: "#64748B",
        testimonials: [
          {
            id: "re-t1",
            quote: "Their guidance helped us secure our dream penthouse under asking.",
            authorName: "OLIVIA ROSS",
            authorRole: "Home Buyer",
          },
          {
            id: "re-t2",
            quote: "We felt informed at every step and never rushed into decisions.",
            authorName: "DANIEL WEBB",
            authorRole: "Investor",
          },
          {
            id: "re-t3",
            quote: "Professional, discreet, and incredibly effective from first call to close.",
            authorName: "MIA CHO",
            authorRole: "Seller",
          },
        ],
      },
      style: {
        desktop: {
          backgroundColor: "#F8FAFC",
          minHeight: 600,
          paddingTop: 90,
          paddingBottom: 90,
        },
      },
      elements: [],
    },
    {
      id: "realestate-footer",
      type: "footer",
      order: 4,
      props: {
        brandName: "ATELIER ESTATES",
        tagline: "Exceptional properties, intelligently represented.",
        bgColor: "#0B1220",
        brandColor: "#F1F5F9",
        taglineColor: "rgba(241,245,249,0.72)",
        dividerColor: "rgba(241,245,249,0.22)",
      },
      style: {
        desktop: {
          backgroundColor: "#0B1220",
          minHeight: 250,
          paddingTop: 40,
          paddingBottom: 40,
        },
      },
      elements: [],
    },
  ],
};
